name: Build FOLIA Minecraft Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build FOLIA
        run: |
          git clone https://github.com/folia-dev/folia.git
          cd folia
          ./gradlew dependencies
          ./gradlew build
